name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test_linux:
    name: asdf plugin test linux
    runs-on: ubuntu-latest
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: ros --version
  plugin_test_macos:
    name: asdf plugin test macos
    runs-on: macos-latest
    steps:
      - name: setup homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: asdf plugin test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: ros --version
