name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test_linux:
    name: asdf plugin test linux
    runs-on: ubuntu-latest
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: ros --version
  plugin_test_macos:
    name: asdf plugin test macos
    runs-on: macos-latest
    steps:
      - name: asdf_plugin_test
        uses: - asdf-vm/actions/plugin-test@v3
                Homebrew/actions/setup-homebrew@master
        with:
          command: ros --version
